# Site settings
title: The Digital Economy of Time
email: igor@borisoglebski.com
url: https://timetick.org
description: "How do you value your time?"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: The Digital Economy of Time

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/economyoftime
  - title: instagram
    url: https://www.instagram.com/economyoftime/
  - title: github
    url: https://github.com/economyoftime

# Build settings
markdown: kramdown
permalink: pretty
